🚀 Fix the magical paginate function and sprinkle in a tiny sdk.wait function ⏳✨
reworkd/harambe pull request #43
Opened 2024-08-16 00:12 UTC by mohamedmamdouh22

I wrapped the recursive call to the function withing try-except block to avoid considering errors in the scraping code as end of the pagination
Also added tiny sdk.wait function to replace page.wait_for_selector, it will just wait for load and the selector

2024-08-16 01:19 UTC, awtkns commented on harambe/core.py
> +                    raise Exception(e)
it should catch on line 225 no?

2024-08-19 21:44 UTC, asim-shrestha commented on harambe/parser/type_currency.py
> +        return parsed_value
good stuff

2024-08-19 21:44 UTC, asim-shrestha commented on harambe/parser/type_currency.py
> +class ParserTypeCurrency:
Good stuff

2024-08-19 21:46 UTC, awtkns requested changes

2024-08-19 21:46 UTC, awtkns commented on harambe/parser/type_currency.py
> +            raise ValueError(f"Unable to parse input as currency: {value}")
there is no point re-raising the same error

```suggestion
        parsed_value = float(value)
```

2024-08-19 21:47 UTC, awtkns commented on harambe/core.py
> +                    raise Exception(e)
lets remove the try catch here its redundant

2024-08-20 02:33 UTC, awtkns approved these changes

2024-08-20 02:33 UTC, awtkns commented
please also bump the version in the pyproject.toml so we can release this :)

2024-08-20 02:34 UTC, merged